title:            Gil Gomes
description:      Speaking up my thoughts about the IT world.
disqus_shortname: gilgomes
reading_time:     true
words_per_minute: 200
#Your site's domain goes here. Leave localhost server or blank when working locally.
url:              http://gilgomes.com.br

# Owner/author information
owner:
  name:           Gil Gomes
  avatar:         gil.JPG
  bio:            "Bachelor in Information Systems. Speaking up my thoughts about the IT world."
  email:          gilgomesp@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        gil27
  facebook:
  github:         gil27
  stackexchange:  
  linkedin:       
  instagram:      gilgomesp
  flickr:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  # google plus id, include the '+', eg +mmistakes
  google_plus:    #+yourid

# Background image to be tiled on all pages
background: 

# Analytics and webmaster tools stuff goes here
google_analytics: UA-36064515-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in top navigation
# For external links add external: true
links:
  # - title: Theme Setup
  #   url: /theme-setup
  # - title: External Link
  #   url: http://mademistakes.com
  #   external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Sao_Paulo
future:      true
highlighter: pygments
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
